PHARMACY BRANCHES

branches (Филиалы):
  id ( INTEGER, PRIMARY KEY )
  address ( VARCHAR(128), NOT NULL )
  time_open ( TIME WITHOUT TIMEZONE, NOT NULL )
  time_close ( TIME WITHOUT TIMEZONE, NOT NULL )
employees (Сотрудники):
  id ( INTEGER, PRIMARY KEY )
  name ( VARCHAR(32), NOT NULL )
  surname ( VARCHAR(32), NULL, DEFAULT - "" )
  login ( VARCHAR(32), NOT NULL )
  password ( VARCHAR(256), NOT NULL )
  position_id ( INTEGER, NOT NULL, FK )
  branch_id ( INTEGER, NOT NULL, FK )
manufacturers (Производители):
  id ( INTEGER, PRIMARY KEY )
  title ( VARCHAR(64), NOT NULL )
  address ( VARCHAR(128), NULL, DEFAULT - "Адрес не указан" )
  requisites ( VARCHAR(256), NULL, DEFAULT - "" )
medicaments (Препараты):
  id ( INTEGER, PRIMARY KEY )
  title ( VARCHAR(64), NOT NULL )
  description ( VARCHAR(512), NULL, DEFAULT - "Описание отсутствует" )
  image_url ( VARCHAR(512), NULL, DEFAULT - "" )
  category_id ( INTEGER, NOT NULL, FK )
  manufacturer_id ( INTEGER, NOT NULL, FK )
  price ( REAL, NOT NULL )
positions (Должности):
  id ( INTEGER, PRIMARY KEY )
  title ( VARCHAR(64), NOT NULL )
categories (Категории):
  id ( INTEGER, PRIMARY KEY )
  title ( VARCHAR(64), NOT NULL )
orders (Продажи):
  id ( INTEGER, PRIMARY KEY )
  branch_id ( INTEGER, NOT NULL, FK )
  employee_id ( INTEGER, NOT NULL, FK )
  amount ( REAL, NULL, DEFAULT - 0 )
  date ( TIMESTAMP, NOT NULL, DEFAULT - NOW() )
orders_details (Продажи инфо):
  id ( INTEGER, PRIMARY KEY )
  order_id ( INTEGER, NOT NULL, FK )
  medicament_id ( INTEGER, NOT NULL, FK )
  count ( INTEGER, NULL, DEFAULT - 1 )


По интерфейсу:
  - Авторизация +
  - Отображение коллег в филиале, в котором работает авторизованный сотрудник +
  - Поиск препаратов по названию / категории / ключевым словам в описании + 
  - Добавление / изменение / удаление препарата (доступно для управляющего филиалом) + + +
  - Просмотр продаж по филиалам +
  - Оформление продажи